### ISSUE TITLE
t5模型疑问和复现问题

### ISSUE THREAD

**Issue by yxk9810** [thunlp/WebCPM#10]
使用数据make_data的数据，然后source:2048 ,target:1024, 测试任务Fact 生成
1.使用mengzi-t5 设置2048的话，大于512的长度都会失去位置信息吧？这个有特殊的处理和优化？
2. 我使用seq2seq 实现的代码，跑出来的结果rouge-l 与论文的61.9差距比较大，代码参考：https://colab.research.google.com/drive/1gXcjGRQHtPU4So4EIktrUBUo4EStp89-?usp=sharing ，请问参数什么的是否不对？或者是有其他的地方需要注意。

**Comment by thuqinyj16** [comment]
您好，感谢对我们论文的关注。
1. 因为我们论文里跑abstract的时候，输出的内容是待摘取内容的前N个字和后N个字，所以target length实际上没有取特别大。对于answer synthesis需要取得稍微大一点（我刚找对应同学确认了实际长度，synthesis model的decode max length是512，其他模块的都是128）。
2. 第二个问题，我看了你的代码，发现你load的数据是我们pipeline data的数据，这一部分数据不是论文里使用的，是我们后续开发了的一个简单能直接跑的pipeline，具体的数据都是调用text-davinci构造的，发现这个pipeline效果很不错。我们论文里使用的数据是interactive_data（https://github.com/thunlp/WebCPM/tree/main/data/interactive_data），也就是都是人工标注的。相比于人工标注，text-davinci摘取的内容通常会做一定程度的修改/总结；相反，人工摘取是严格的摘取其中的一段内容，所以在人工数据上训练/测试出来的模型rouge-L会显著得更高一点。

**Comment by yxk9810** [comment]
感谢回答，是我看错了，我看下interactive的数据
