### ISSUE TITLE
cpm_10b_webcpm_exp.pt是经过了WebCPM数据训练过的吗?还是只是一个预训练语言模型？

### ISSUE THREAD

**Issue by liangbin123** [thunlp/WebCPM#11]
你好，很感谢你们的工作，你们揭开了CloseAI一直没有透露的WebGPT的神秘面纱，让大众能够了解到里面的细节。
你们的工作很有价值，而在你们的readme里提到的这个cpm_10b_webcpm_exp.pt模型，是已经经过了你们构造的数据训练过吗？还是只是一个预训练模型，需要用户自行finetune？

**Comment by thuqinyj16** [comment]
只是一个裸的没有finetune过的模型，需要自行finetune，不过我也可以提供finetune后的模型（传的有点慢，尽量这周内完成）

**Comment by liangbin123** [comment]
好的，期待您finetune后的模型，感谢。

**Comment by liangbin123** [comment]
> 只是一个裸的没有finetune过的模型，需要自行finetune，不过我也可以提供finetune后的模型（传的有点慢，尽量这周内完成）
好的，期待您finetune后的模型，感谢。
