### ISSUE TITLE
os.environ.keys()没有‘MASTER_PORT’

### ISSUE THREAD

**Issue by FutureForMe** [thunlp/WebCPM#12]
您好，最近调研到您的工作，感觉这个工作非常有价值，填补了国内的空白！

我在复现您的代码的时候，遇到了一个小bug，尝试了许多方法仍然没有解决，所以想问一下您。错误如下：

  File "finetune_cpm_bee.py", line 78, in initialize
    os.environ["MASTER_PORT"] = str(int(os.environ["MASTER_PORT"]) + 12)
  File "/usr/local/lib/python3.8/os.py", line 673, in __getitem__
    raise KeyError(key) from None
KeyError: 'MASTER_PORT

我对我服务器的os.environ.keys()进行了输出，发现确实没有'MASTER_PORT'这个key，也没有分布式需要的其他key，例如WORLD_SIZE，RANK等，我想问一下这是什么原因导致的？是需要安装一些特有库吗？

**Comment by thuqinyj16** [comment]
您好，这一行“os.environ["MASTER_PORT"] = str(int(os.environ["MASTER_PORT"]) + 12)”代码可以注释掉哈，不影响模型训练，我忘记注释了

**Comment by FutureForMe** [comment]
您好，我按照您的方法注释掉了这一行，但是在bmtrain/init.py这里又会报错，提示没有LOCAL_RANK，错误如下：
Traceback (most recent call last):
  File "finetune_cpm_bee.py", line 404, in <module>
    main()
  File "finetune_cpm_bee.py", line 398, in main
    args = initialize()
  File "finetune_cpm_bee.py", line 80, in initialize
    bmt.init_distributed(seed=args.seed)
  File "/usr/local/lib/python3.8/site-packages/bmtrain/init.py", line 44, in init_distributed
    local_rank = int(os.environ["LOCAL_RANK"])
  File "/usr/local/lib/python3.8/os.py", line 673, in __getitem__
    raise KeyError(key) from None
KeyError: 'LOCAL_RANK'

请教一下这种问题应该如何解决呀？

**Comment by thuqinyj16** [comment]
请问您执行的脚本是什么呢？bash **.sh 我们在https://github.com/thunlp/WebCPM/blob/main/training/scripts/finetune_cpm_bee.sh 这里都是设置过的

**Comment by FutureForMe** [comment]
我是直接运行的finetune_cpm_bee.py，出现了上述错误。我改成运行finetune_cpm_bee.sh之后未报错。十分感谢您的回复！

**Comment by FutureForMe** [comment]
作者，您好，我还有一个问题想请假一下。
我看您的论文里面说是为action prediction, search query generation 和 supporting fact extraction三个任务分别训练了单独的模型，要是再加上Synthesis Model，是不是就需要分别训练4个CPM-10B的模型负责这四个模块？

**Comment by thuqinyj16** [comment]
是的，其实也可以直接multi-task训练到一个模型里，这样你inference的时候load这一个模型进GPU就可以，比较方便

**Comment by FutureForMe** [comment]
OK，了解。谢谢您的回复！

**Comment by FutureForMe** [comment]
multi-task训练的话，对模型精度影响大吗？

**Comment by thuqinyj16** [comment]
效果会稍微降一点，但对于10B模型来说能接受

**Comment by FutureForMe** [comment]
OK，明白。太感谢你的回复了，抱拳了！
