### ISSUE TITLE
pipeline方式模型

### ISSUE THREAD

**Issue by process-cxr** [thunlp/WebCPM#14]
你好，我看到interactive网页搜索方法是训练两个模型检索模型和合成模型，pipeline的方式没有提及，是只训练了一个整体模型嘛？还是也训练两个，如果训练了两个的话，合成模型是使用那儿的数据，pipeline_data的数据看起来像是只训练检索用的？

**Comment by thuqinyj16** [comment]
pipeline可以直接把所有任务都multi-task训练，pipeline_data本身也包含answer synthesis数据

**Comment by process-cxr** [comment]
好的，谢谢，是直接训练一个多任务模型的话就没问题了

**Comment by process-cxr** [comment]
除了交互式网页搜索数据外，我们还提供了训练流水线式网页搜索所需的数据集：pipeline_data（总共110k 个实例）。所有数据均由text-davinci-003创建，然后由人类注释者手动筛选。 我在文档中看到这句话，请问pipeline_data收集到的数据不是由bing api检索得到嘛，全由text-davinci-003创建的话还能算是和检索有关吗。

**Comment by thuqinyj16** [comment]
造数据的过程中bing search也调用的，返回的结果喂给davinci来造数据，不是全都由davinci自己生成的

**Comment by process-cxr** [comment]
好的，谢谢

**Comment by process-cxr** [comment]
如果训练数据是davinci利用bing search返回的结果造出来的，那么训练出来的这个pipeline的模型在inference的时候，岂不是也不能直接处理bing search的结果，而是必须也要走一遍davinci处理的流程？

**Comment by thuqinyj16** [comment]
不是的，训完的模型具备davinci使用搜索引擎的能力，是能直接使用的，参考代码https://github.com/thunlp/WebCPM/blob/main/run_web_browsing/run_pipeline.py
训练过的模型也有（https://cloud.tsinghua.edu.cn/d/a02ae00b11434c9c8560/），参考README的下载方法

**Comment by process-cxr** [comment]
看到了，谢谢
