### ISSUE TITLE
能提供下baidu网盘的下载地址吗

### ISSUE THREAD

**Issue by datalee** [thunlp/WebCPM#15]
interactive_data/data.json is the dataset used in the experiments of the paper (5500 instances in total). interactive_data/data_zhihu.json is additional dataset collected alongside this paper (~900 instances), with the question sourcing from [Zhihu](https://www.zhihu.com/people/71-26-1-50), you can use this for data augmentation.

**Comment by thuqinyj16** [comment]
See https://cloud.tsinghua.edu.cn/d/eaac53d406a540bb9434/

**Comment by datalee** [comment]
> See https://cloud.tsinghua.edu.cn/d/eaac53d406a540bb9434/

三克油，非常的感谢，yyds
