### ISSUE TITLE
bmtrain import错误

### ISSUE THREAD

**Issue by jiangix-paper** [thunlp/WebCPM#16]
你好，python3.10安装bmtrain，显示安装成功，但是import bmtrain时，报这个错误：/bmtrain/nccl/_C.cpython-310-x86_64-linux-gnu.so: undefined symbol: ncclBroadcast。torch版本是2.0.0

**Comment by thuqinyj16** [comment]
您好，bmtrain 目前不支持 torch 2.0，<2.0的都可以，麻烦对torch降级哈
