### ISSUE TITLE
运行流水线式网页搜索出错

### ISSUE THREAD

**Issue by aistoy** [thunlp/WebCPM#18]
Traceback (most recent call last):
  File "/content/WebCPM/run_web_browsing/run_pipeline.py", line 182, in <module>
    pred_dict = model_predict_cpmb(modelcpmb, tokenizer_cpmb, question, max_abstract_num=5, whether_corrupt_abstract=False)
  File "/content/WebCPM/run_web_browsing/run_pipeline.py", line 57, in model_predict_cpmb
    searched_results = op.search(query)
  File "/content/WebCPM/run_web_browsing/interaction/platformctrl_pipeline.py", line 48, in search
    return self.content[-1].data["webPages"]["value"]
KeyError: 'webPages'
Traceback (most recent call last):
  File "/content/WebCPM/run_web_browsing/run_pipeline.py", line 185, in <module>
    dump_list.append(pred_dict)
NameError: name 'pred_dict' is not defined

search返回结果json中可能没有webPages字段，需要处理下

**Comment by thuqinyj16** [comment]
可以打印一下你返回的结果self.content[-1].data内容吗？是否是每次执行的时候都会报错？

**Comment by thuqinyj16** [comment]
BING_SEARCH_KEY=“”这个是否有提供？        
result = requests.get(endpoint, headers=headers, params={'q': key_words, 'mkt': mkt }, timeout=10)
        if result.status_code == 200:
            result = result.json()

            self.content = []
            self.content.append(ContentItem(CONTENT_TYPE.SEARCH_RESULT, result))
这一段代码是否有正确执行，得到bing search的返回结果？

**Comment by aistoy** [comment]
BING_SEARCH_KEY没有问题，看打印输出是经过几次search后会有一次这样的错误，我需要复现下再将result贴出来。不过我也可以去查看下bing search api的文档，看是不是存在某些情况返回json中没有webPages字段。

**Comment by aistoy** [comment]
https://learn.microsoft.com/en-us/bing/search-apis/bing-web-search/reference/response-objects#searchresponse

> SearchResponse
The response's top-level object for search requests that succeed.

By default, the Search API includes all relevant answers unless:

The query specifies the [responseFilter](https://learn.microsoft.com/en-us/bing/search-apis/bing-web-search/reference/query-parameters#responsefilter) query parameter to limit the answers it returns.
One or more of the search components does not return results (for example, no news results are relevant to the query).
The subscription key does not have access to the search component.
If the service suspects a denial of service attack, the request succeeds (HTTP status code is 200 OK), but the body of the response is empty.
-----
bing搜索是有可能返回status_code == 200 ，但body为空的，我是在google colab里面运行的，不知道会不会偶尔会让bing误判为service attack。 代码这里最好加个判断是否存在webPages

**Comment by thuqinyj16** [comment]
支持了一个版本在这里：[15ded5a6f6b73a6e4b54f7c4663fc88523d47a94  ](https://github.com/thunlp/WebCPM/commit/15ded5a6f6b73a6e4b54f7c4663fc88523d47a94) 您也可以尝试其他的实现方案

**Comment by aistoy** [comment]
这样修改可以了
