### ISSUE TITLE
关于流水线网页搜索工作流程

### ISSUE THREAD

**Issue by aistoy** [thunlp/WebCPM#19]
README中提到流水线网页工作流程包括四个阶段：

> （1）首先，根据原始问题生成可能的搜索查询；（2）然后，对每个搜索查询，调用Bing搜索并访问前K个网页；（3）对于每个网页，提取重要信息；（4）基于所有记录的信息，生成连贯且细致的答案。

关于阶段2）只是简单的调用Bing搜索的前k个页面吗？你们的论文中提到这里应该是有个action prediction模块进行动作预测来选择一个页面的吧，不是简单的只取排在前面的k个页面吧

**Comment by thuqinyj16** [comment]
如README里说的，pipeline方式不是论文里的内容，交互式方式才是论文里的内容。pipeline的数据/算法实现是这个仓库额外提供的。交互式方式的run_web_browsing代码一周内会给到，但是数据/训练/inference的代码都是有的

**Comment by aistoy** [comment]
谢谢！了解，期待交互式方式的实现。另外，想请教下，交互式方式和流水线方式在依照原始问题生成可能搜索查询，网页信息提取，最后答案生成这几部分应该是差不多的吧

**Comment by thuqinyj16** [comment]
是的

**Comment by aistoy** [comment]
ok， tks！
