### ISSUE TITLE
关于模型模仿人类搜索行为的一些问题

### ISSUE THREAD

**Issue by aistoy** [thunlp/WebCPM#20]
简单了解了下WebCPM和WebGPT，应该都是训练LLM学会使用Search Engine，通过搜索结果来总结生成答案。都有人类behavior clone过程，对这个过程有两个疑问：
1.模型是否有必要模仿学习人类行为？
对于人类来说对搜索结果经常会翻页，返回，筛选，是因为受人类阅读速度和时间影响，耐性有限，从而会快速挑选其中的搜索结果进行阅读总结。但对于机器来说不存在这样的问题，机器应该是阅读尽量多的相关页面来进行信息摘要和事实提取，最后总结生成答案，这样答案才更完整和真实吧。

2.搜索引擎排序算法的变动或更换搜索引擎是否都会对模型的性能产生影响？
目前模型是通过bing search来训练的，如果bing search对排序算法进行了变动，搜索结果的排序变了，或者使用其他引擎。是不是对整个搜索行为学习都有影响，需要重新训练。

**Comment by thuqinyj16** [comment]
1. 确实模仿人类行为不是必须的，但是是一条可行、方便的路子（否则需要让机器自行探索交互的模式，这方面的研究还比较欠缺，不过也是值得探索的）。机器确实应该有自己的接口 / 使用工具的方式，人类受限于感受器、处理器速度等原因无法以最高效的方式和搜索引擎交互。
2. 影响不大。搜索引擎返回的结果大同小异，这方面的迁移成本不是很大，直接接其他的搜索引擎效果不会变化很大。

**Comment by aistoy** [comment]
我看你们论文6.2 Holistic Pipeline Evaluation里面说
>
  (3) The facts gathered
by non-interactive search lead to slightly worse performance (7.5%+18% = 25.5%) than our search
model. The superiority of our search model over
non-interactive search may be because our model
(a) sends diverse queries to Bing multiple times so
that more abundant information can be retrieved,
and (b) it critically decides whether a web page contains important information, which performs
better than TF-IDF.

这个意思是non-interactive search相对差些的原因是：1）只有原始输入搜索，没有相关多次搜索，2）页面重要信息获取上也不足？如果是这样的话，由于现在WebCPM几个模块是相对独立的，可以先调用搜索生成模块进行多次搜索，再使用现在的事实提取模块来对每次搜索的topk页面进行提取？这样是不是就是你们现在的流水线模式的工作方式？
