### ISSUE TITLE
请问这个WebCPM模型不开源是吗，需要自己根据数据集训练得到，在单张4090上可以运行吗？

### ISSUE THREAD

**Issue by Lufffya** [thunlp/WebCPM#21]

**Comment by aistoy** [comment]
文档里面有提到pipeline微调模型的下载方法：

> 同时我们也提供了基于pipeline的微调后的模型，请参考download_model_pipeline_finetuned.sh，或者您也可以在这里手动下载：[Tsinghua Cloud](https://cloud.tsinghua.edu.cn/d/3dc39eccc6c64bb58671/)。

我下载后在google drive上也共享了一份：https://drive.google.com/file/d/1cr4jGsmcd9w0iFOhWc03okLOfFMEQkH2/view?usp=drive_link

**Comment by thuqinyj16** [comment]
感谢关注！基于pipeline跑的模型已经开源（checkpoint放出来了），基于interactive web search的模型我尽快放一下
