### ISSUE TITLE
模型加速

### ISSUE THREAD

**Issue by Kerry0123** [thunlp/WebCPM#22]
您好，目前应用部署在V100s上，1s约生成10个字左右，请问下是否可以提供模型推理加速的一些方案，谢谢

**Comment by thuqinyj16** [comment]
您好，cpmb的加速的方案本身不是在这个仓库维护的，您可以参考一下https://github.com/OpenBMB/BMCook/tree/main 和 https://github.com/OpenBMB/BMTrain/tree/main/bmtrain 这里的量化方案，是能够加速的
