### ISSUE TITLE
为什么去掉引用?

### ISSUE THREAD

**Issue by yangjingyuan** [thunlp/WebCPM#24]
你好，请问下你们在interactive方式下，把cite去掉了是吧？

我看make_data_synthesis_model.py 会去掉引用，这个是为什么呢？

**Comment by thuqinyj16** [comment]
这个信息我们虽然收集了，但是没有用到（所以就直接去掉了）。期待在后续工作中利用这部分信息实现更加完善的长文本问答。

**Comment by yangjingyuan** [comment]
明白了，多谢了哈
