### ISSUE TITLE
引用问题

### ISSUE THREAD

**Issue by majinmin** [thunlp/WebCPM#25]
您好，请问一下，模型是根据摘要+文本输入大模型中的吗，我看模型输出并没有具体的引用结果啊，比如xxxxxxxxxxxxxxxxx[1],xxxxxxxxxxxxxxxxxxxx[2]。每一个话有一个引用，但是这个功能是没有吗

**Comment by thuqinyj16** [comment]
您好，引用这个信息我们虽然收集了，但是没有用到（所以就直接去掉了）。期待在后续工作中利用这部分信息实现更加完善的长文本问答。
