### ISSUE TITLE
How to try using T5

### ISSUE THREAD

**Issue by a101269** [thunlp/WebCPM#5]
Great job, but CPM is too big for me. How can I use a small model like T5 or ChatGLM6B

**Comment by thuqinyj16** [comment]
Hi thanks for the interests in our work! You can try data preprocessing (training/dataset_interactive/make_data_search_model.py and training/dataset_pipeline/make_data.py) to obtain the training and test data, then use other repositories like T5 to train your own model. After training, you can modify the inference codes in this repo to do testing.
